/**
 * Core In-Memory State & Relational Store
 * Seeded with authentic Tanzanian Microfinance Institutions data
 */
import {
  AuditLog,
  Branch,
  ChartOfAccount,
  Customer,
  JournalEntry,
  LendingGroup,
  Loan,
  LoanApplication,
  LoanProduct,
  OfflineSyncRecord,
  Payment,
  ProviderWebhookTransaction,
  SavingsAccount,
  SavingsTransaction,
  User,
} from '../types';
import { generateRepaymentSchedule } from '../engines/scheduleEngine';

export const INITIAL_BRANCHES: Branch[] = [
  {
    id: 'br-kariakoo',
    code: 'BR-DAR-01',
    name: 'Kariakoo Branch (Dar es Salaam)',
    region: 'Dar es Salaam',
    district: 'Ilala',
    phone: '+255 22 218 4001',
    status: 'ACTIVE',
  },
  {
    id: 'br-arusha',
    code: 'BR-ARU-01',
    name: 'Arusha Urban Branch',
    region: 'Arusha',
    district: 'Arusha City',
    phone: '+255 27 254 8100',
    status: 'ACTIVE',
  },
  {
    id: 'br-mwanza',
    code: 'BR-MWA-01',
    name: 'Mwanza Lake Branch',
    region: 'Mwanza',
    district: 'Nyamagana',
    phone: '+255 28 250 0920',
    status: 'ACTIVE',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-amina',
    username: 'amina.manager',
    firstName: 'Amina',
    lastName: 'Kimaro',
    email: 'amina.kimaro@tusonge-mfi.co.tz',
    phone: '+255 754 100 201',
    role: 'BRANCH_MANAGER',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-amina-ho',
    username: 'amina.ho',
    firstName: 'Amina',
    lastName: 'Mwamba',
    email: 'amina.mwamba@tusonge-mfi.co.tz',
    phone: '+255 754 100 201',
    role: 'HEAD_OFFICE_MANAGER',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-baraka',
    username: 'baraka.field',
    firstName: 'Baraka',
    lastName: 'Mushi',
    email: 'baraka.mushi@tusonge-mfi.co.tz',
    phone: '+255 767 220 301',
    role: 'FIELD_OFFICER',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-baraka-bm',
    username: 'baraka.bm',
    firstName: 'Baraka',
    lastName: 'Mkumbo',
    email: 'baraka.mkumbo@tusonge-mfi.co.tz',
    phone: '+255 767 220 301',
    role: 'BRANCH_MANAGER',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-daudi',
    username: 'daudi.accountant',
    firstName: 'Daudi',
    lastName: 'Mrema',
    email: 'daudi.mrema@tusonge-mfi.co.tz',
    phone: '+255 713 330 401',
    role: 'ACCOUNTANT',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-daudi-lo',
    username: 'daudi.lo',
    firstName: 'Daudi',
    lastName: 'Kibona',
    email: 'daudi.kibona@tusonge-mfi.co.tz',
    phone: '+255 713 330 401',
    role: 'LOAN_OFFICER',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-neema',
    username: 'neema.auditor',
    firstName: 'Neema',
    lastName: 'Massawe',
    email: 'neema.massawe@tusonge-mfi.co.tz',
    phone: '+255 768 660 701',
    role: 'AUDITOR',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-neema-aud',
    username: 'neema.aud',
    firstName: 'Neema',
    lastName: 'Lyimo',
    email: 'neema.lyimo@tusonge-mfi.co.tz',
    phone: '+255 768 660 701',
    role: 'AUDITOR',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-admin',
    username: 'admin',
    firstName: 'System',
    lastName: 'Admin',
    email: 'admin@imara-mfi.co.tz',
    phone: '+255 754 000 001',
    role: 'SUPER_ADMIN',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-superadmin',
    username: 'superadmin',
    firstName: 'Super',
    lastName: 'Admin',
    email: 'superadmin@imara-mfi.co.tz',
    phone: '+255 754 000 002',
    role: 'SUPER_ADMIN',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-rehema',
    username: 'rehema.co',
    firstName: 'Rehema',
    lastName: 'Shaban',
    email: 'rehema.shaban@tusonge-mfi.co.tz',
    phone: '+255 784 440 501',
    role: 'COLLECTION_OFFICER',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-juma',
    username: 'juma.acc',
    firstName: 'Juma',
    lastName: 'Mussa',
    email: 'juma.mussa@tusonge-mfi.co.tz',
    phone: '+255 755 550 601',
    role: 'ACCOUNTANT',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-neema',
    username: 'neema.aud',
    firstName: 'Neema',
    lastName: 'Lyimo',
    email: 'neema.lyimo@tusonge-mfi.co.tz',
    phone: '+255 768 660 701',
    role: 'AUDITOR',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
  {
    id: 'usr-grace',
    username: 'grace.cust',
    firstName: 'Grace',
    lastName: 'Kimaro',
    email: 'grace.kimaro@gmail.com',
    phone: '+255 712 998 811',
    role: 'CUSTOMER',
    branchId: 'br-kariakoo',
    status: 'ACTIVE',
  },
];

export const INITIAL_PRODUCTS: LoanProduct[] = [
  {
    id: 'prod-biashara',
    code: 'LP-BIASHARA',
    name: 'Biashara Micro Business Loan',
    description: 'Working capital financing for market vendors, retail shops and small enterprises in urban commercial hubs.',
    minPrincipal: 300000,
    maxPrincipal: 5000000,
    annualNominalRate: 18.0,
    interestMethod: 'FLAT',
    dayCountConvention: 'ACTUAL_365',
    repaymentFrequency: 'MONTHLY',
    minTerm: 3,
    maxTerm: 12,
    gracePeriodType: 'NONE',
    gracePeriodInstallments: 0,
    processingFeePercent: 2.5,
    latePenaltyDailyPercent: 0.1,
    paymentAllocationStrategy: 'PENALTY_FEE_INTEREST_PRINCIPAL',
    overpaymentPolicy: 'NEXT_INSTALLMENT',
    status: 'ACTIVE',
  },
  {
    id: 'prod-kilimo',
    code: 'LP-KILIMO',
    name: 'Kilimo Agri Seasonal Booster',
    description: 'Seasonal crop input and farming loan tailored with post-planting grace periods.',
    minPrincipal: 500000,
    maxPrincipal: 10000000,
    annualNominalRate: 15.0,
    interestMethod: 'DECLINING_BALANCE',
    dayCountConvention: '30_360',
    repaymentFrequency: 'MONTHLY',
    minTerm: 6,
    maxTerm: 18,
    gracePeriodType: 'PRINCIPAL_ONLY',
    gracePeriodInstallments: 2,
    processingFeePercent: 2.0,
    latePenaltyDailyPercent: 0.08,
    paymentAllocationStrategy: 'PENALTY_FEE_INTEREST_PRINCIPAL',
    overpaymentPolicy: 'PRINCIPAL_PREPAYMENT',
    status: 'ACTIVE',
  },
  {
    id: 'prod-group',
    code: 'LP-TUJIKWAMUE',
    name: 'Tujikwamue Group Solidarity Loan',
    description: 'Peer-guaranteed microcredit for women and youth groups meeting weekly/biweekly.',
    minPrincipal: 200000,
    maxPrincipal: 2000000,
    annualNominalRate: 21.0,
    interestMethod: 'EQUAL_INSTALLMENT',
    dayCountConvention: 'ACTUAL_365',
    repaymentFrequency: 'BIWEEKLY',
    minTerm: 6,
    maxTerm: 12,
    gracePeriodType: 'NONE',
    gracePeriodInstallments: 0,
    processingFeePercent: 1.5,
    latePenaltyDailyPercent: 0.15,
    paymentAllocationStrategy: 'PENALTY_FEE_INTEREST_PRINCIPAL',
    overpaymentPolicy: 'NEXT_INSTALLMENT',
    status: 'ACTIVE',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-grace',
    customerNumber: 'CUST-202401-0081',
    branchId: 'br-kariakoo',
    firstName: 'Grace',
    middleName: 'Emanuel',
    lastName: 'Kimaro',
    dateOfBirth: '1988-04-12',
    gender: 'FEMALE',
    phonePrimary: '+255 712 998 811',
    email: 'grace.kimaro@gmail.com',
    nationalIdNumber: '19880412-14101-00002-23',
    status: 'ACTIVE',
    businessType: 'Fabrics & Kanga Retail Wholesale',
    monthlyRevenue: 3800000,
    monthlyExpenses: 2100000,
    groupId: 'grp-upendo',
    documents: [
      {
        id: 'doc-1',
        documentType: 'NIDA',
        documentNumber: '19880412-14101-00002-23',
        issueDate: '2020-01-15',
        storageRef: 's3://kyc/cust-grace/nida_card.pdf',
        verificationStatus: 'VERIFIED',
        verifiedBy: 'Baraka Mkumbo',
        verifiedAt: '2024-01-10',
      },
      {
        id: 'doc-2',
        documentType: 'LOCAL_GOV_LETTER',
        documentNumber: 'MTAA-KKO-891',
        issueDate: '2024-01-05',
        storageRef: 's3://kyc/cust-grace/mtaa_intro.pdf',
        verificationStatus: 'VERIFIED',
        verifiedBy: 'Baraka Mkumbo',
        verifiedAt: '2024-01-10',
      },
    ],
    createdAt: '2024-01-08T09:30:00Z',
  },
  {
    id: 'cust-selemani',
    customerNumber: 'CUST-202402-0142',
    branchId: 'br-kariakoo',
    firstName: 'Selemani',
    middleName: 'Bakari',
    lastName: 'Msangi',
    dateOfBirth: '1982-11-23',
    gender: 'MALE',
    phonePrimary: '+255 754 445 566',
    email: 'selemani.msangi@gmail.com',
    nationalIdNumber: '19821123-11102-00005-19',
    status: 'ACTIVE',
    businessType: 'Motorcycle Spares & Garage',
    monthlyRevenue: 4500000,
    monthlyExpenses: 2800000,
    documents: [
      {
        id: 'doc-3',
        documentType: 'NIDA',
        documentNumber: '19821123-11102-00005-19',
        issueDate: '2019-08-20',
        storageRef: 's3://kyc/cust-sele/nida.pdf',
        verificationStatus: 'VERIFIED',
        verifiedBy: 'Baraka Mkumbo',
        verifiedAt: '2024-02-01',
      },
    ],
    createdAt: '2024-02-01T11:15:00Z',
  },
  {
    id: 'cust-zawadi',
    customerNumber: 'CUST-202403-0219',
    branchId: 'br-kariakoo',
    firstName: 'Zawadi',
    middleName: 'Joseph',
    lastName: 'Mrema',
    dateOfBirth: '1992-06-08',
    gender: 'FEMALE',
    phonePrimary: '+255 765 890 123',
    email: 'zawadi.mrema@gmail.com',
    nationalIdNumber: '19920608-21203-00001-44',
    status: 'ACTIVE',
    businessType: 'Produce & Grain Supply',
    monthlyRevenue: 2900000,
    monthlyExpenses: 1600000,
    groupId: 'grp-upendo',
    documents: [
      {
        id: 'doc-4',
        documentType: 'VOTER_ID',
        documentNumber: 'T-1029-4401-2',
        issueDate: '2020-03-10',
        storageRef: 's3://kyc/cust-zawadi/voter.pdf',
        verificationStatus: 'VERIFIED',
        verifiedBy: 'Daudi Kibona',
        verifiedAt: '2024-03-02',
      },
    ],
    createdAt: '2024-03-01T14:00:00Z',
  },
  {
    id: 'cust-jumanne',
    customerNumber: 'CUST-202404-0305',
    branchId: 'br-arusha',
    firstName: 'Jumanne',
    middleName: 'Kassim',
    lastName: 'Mollel',
    dateOfBirth: '1979-09-17',
    gender: 'MALE',
    phonePrimary: '+255 782 112 334',
    email: 'jumanne.mollel@yahoo.com',
    nationalIdNumber: '19790917-31105-00007-88',
    status: 'ACTIVE',
    businessType: 'Horticulture & Vegetable Farm',
    monthlyRevenue: 5200000,
    monthlyExpenses: 3100000,
    documents: [
      {
        id: 'doc-5',
        documentType: 'NIDA',
        documentNumber: '19790917-31105-00007-88',
        issueDate: '2019-12-05',
        storageRef: 's3://kyc/cust-jumanne/nida.pdf',
        verificationStatus: 'VERIFIED',
        verifiedBy: 'Amina Mwamba',
        verifiedAt: '2024-04-12',
      },
    ],
    createdAt: '2024-04-10T10:00:00Z',
  },
];

export const INITIAL_GROUPS: LendingGroup[] = [
  {
    id: 'grp-upendo',
    groupNumber: 'GRP-2024-0012',
    branchId: 'br-kariakoo',
    name: 'Upendo Women Solidarity Group',
    leaderCustomerId: 'cust-grace',
    loanOfficerId: 'usr-daudi',
    meetingFrequency: 'WEEKLY',
    meetingDayOfWeek: 2, // Tuesday
    meetingLocation: 'Msimbazi Community Hall, Kariakoo',
    status: 'ACTIVE',
    memberIds: ['cust-grace', 'cust-zawadi'],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'grp-umoja',
    groupNumber: 'GRP-2024-0015',
    branchId: 'br-arusha',
    name: 'Umoja Ni Nguvu Agri Group',
    leaderCustomerId: 'cust-jumanne',
    loanOfficerId: 'usr-daudi',
    meetingFrequency: 'BIWEEKLY',
    meetingDayOfWeek: 4, // Thursday
    meetingLocation: 'Ngaramtoni Center, Arusha',
    status: 'ACTIVE',
    memberIds: ['cust-jumanne'],
    createdAt: '2024-02-10T08:30:00Z',
  },
];

// Pre-compute initial loans
const loan1Schedule = generateRepaymentSchedule({
  loanId: 'ln-grace-01',
  disbursedPrincipal: 2500000,
  annualNominalRate: 18.0,
  interestMethod: 'FLAT',
  repaymentFrequency: 'MONTHLY',
  termInstallments: 6,
  startDate: '2024-02-01',
  gracePeriodType: 'NONE',
  gracePeriodInstallments: 0,
});

// Mark first 3 installments as paid for Grace
loan1Schedule[0].principalPaid = loan1Schedule[0].principalDue;
loan1Schedule[0].interestPaid = loan1Schedule[0].interestDue;
loan1Schedule[0].totalPaid = loan1Schedule[0].totalDue;
loan1Schedule[0].status = 'PAID';

loan1Schedule[1].principalPaid = loan1Schedule[1].principalDue;
loan1Schedule[1].interestPaid = loan1Schedule[1].interestDue;
loan1Schedule[1].totalPaid = loan1Schedule[1].totalDue;
loan1Schedule[1].status = 'PAID';

loan1Schedule[2].principalPaid = loan1Schedule[2].principalDue;
loan1Schedule[2].interestPaid = loan1Schedule[2].interestDue;
loan1Schedule[2].totalPaid = loan1Schedule[2].totalDue;
loan1Schedule[2].status = 'PAID';

const loan2Schedule = generateRepaymentSchedule({
  loanId: 'ln-sele-01',
  disbursedPrincipal: 4000000,
  annualNominalRate: 15.0,
  interestMethod: 'DECLINING_BALANCE',
  repaymentFrequency: 'MONTHLY',
  termInstallments: 8,
  startDate: '2024-01-10',
  gracePeriodType: 'PRINCIPAL_ONLY',
  gracePeriodInstallments: 2,
});

// Simulate Selemani having an overdue installment (In Arrears)
loan2Schedule[0].principalPaid = loan2Schedule[0].principalDue;
loan2Schedule[0].interestPaid = loan2Schedule[0].interestDue;
loan2Schedule[0].totalPaid = loan2Schedule[0].totalDue;
loan2Schedule[0].status = 'PAID';

loan2Schedule[1].principalPaid = loan2Schedule[1].principalDue;
loan2Schedule[1].interestPaid = loan2Schedule[1].interestDue;
loan2Schedule[1].totalPaid = loan2Schedule[1].totalDue;
loan2Schedule[1].status = 'PAID';

// Installment 3 is partially paid and now overdue
loan2Schedule[2].dueDate = '2024-04-10';
loan2Schedule[2].interestPaid = loan2Schedule[2].interestDue;
loan2Schedule[2].principalPaid = 100000;
loan2Schedule[2].totalPaid = loan2Schedule[2].interestPaid + 100000;
loan2Schedule[2].penaltyDue = 45000;
loan2Schedule[2].status = 'OVERDUE';

export const INITIAL_LOANS: Loan[] = [
  {
    id: 'ln-grace-01',
    loanAccountNumber: 'LN-2024-001091',
    applicationId: 'app-grace-01',
    customerId: 'cust-grace',
    customerName: 'Grace Emanuel Kimaro',
    customerPhone: '+255 712 998 811',
    branchId: 'br-kariakoo',
    productId: 'prod-biashara',
    productName: 'Biashara Micro Business Loan',
    groupId: 'grp-upendo',
    groupName: 'Upendo Women Solidarity Group',
    disbursedPrincipal: 2500000,
    outstandingPrincipal: 1250000,
    outstandingInterest: 112500,
    outstandingFees: 0,
    outstandingPenalties: 0,
    totalOutstanding: 1362500,
    daysInArrears: 0,
    status: 'ACTIVE',
    disbursedAt: '2024-02-01T10:00:00Z',
    disbursedBy: 'Baraka Mkumbo',
    maturityDate: '2024-08-01',
    installments: loan1Schedule,
  },
  {
    id: 'ln-sele-01',
    loanAccountNumber: 'LN-2024-001092',
    applicationId: 'app-sele-01',
    customerId: 'cust-selemani',
    customerName: 'Selemani Bakari Msangi',
    customerPhone: '+255 754 445 566',
    branchId: 'br-kariakoo',
    productId: 'prod-kilimo',
    productName: 'Kilimo Agri Seasonal Booster',
    disbursedPrincipal: 4000000,
    outstandingPrincipal: 3333333,
    outstandingInterest: 180000,
    outstandingFees: 0,
    outstandingPenalties: 45000,
    totalOutstanding: 3558333,
    daysInArrears: 32,
    status: 'IN_ARREARS',
    disbursedAt: '2024-01-10T14:30:00Z',
    disbursedBy: 'Baraka Mkumbo',
    maturityDate: '2024-09-10',
    installments: loan2Schedule,
  },
];

export const INITIAL_APPLICATIONS: LoanApplication[] = [
  {
    id: 'app-zawadi-01',
    applicationNumber: 'APP-202409-0044',
    branchId: 'br-kariakoo',
    customerId: 'cust-zawadi',
    customerName: 'Zawadi Joseph Mrema',
    groupId: 'grp-upendo',
    groupName: 'Upendo Women Solidarity Group',
    productId: 'prod-group',
    productName: 'Tujikwamue Group Solidarity Loan',
    appliedPrincipal: 1200000,
    approvedPrincipal: 1200000,
    termInstallments: 8,
    purpose: 'Bulk purchase of maize grain bags during post-harvest price dip',
    status: 'PENDING_APPROVAL',
    loanOfficerId: 'usr-daudi',
    assessment: {
      id: 'ass-zawadi-01',
      assessorId: 'usr-daudi',
      assessorName: 'Daudi Kibona',
      assessedAt: '2024-09-02T10:00:00Z',
      monthlyIncome: 2900000,
      monthlyExpenses: 1600000,
      disposableIncome: 1300000,
      debtToIncomeRatio: 26.5,
      creditScore: 780,
      riskGrade: 'LOW',
      recommendation: 'RECOMMEND_APPROVE',
      notes: 'Active member of Upendo group with exemplary attendance and reliable seasonal cash flow.',
    },
    approvals: [],
    createdAt: '2024-09-01T09:00:00Z',
    updatedAt: '2024-09-02T10:00:00Z',
  },
  {
    id: 'app-jumanne-01',
    applicationNumber: 'APP-202409-0045',
    branchId: 'br-arusha',
    customerId: 'cust-jumanne',
    customerName: 'Jumanne Kassim Mollel',
    groupId: 'grp-umoja',
    groupName: 'Umoja Ni Nguvu Agri Group',
    productId: 'prod-kilimo',
    productName: 'Kilimo Agri Seasonal Booster',
    appliedPrincipal: 4500000,
    termInstallments: 12,
    purpose: 'Drip irrigation pipes and organic fertilizers for greenhouse tomato farm',
    status: 'ASSESSED',
    loanOfficerId: 'usr-daudi',
    assessment: {
      id: 'ass-jumanne-01',
      assessorId: 'usr-daudi',
      assessorName: 'Daudi Kibona',
      assessedAt: '2024-09-05T14:20:00Z',
      monthlyIncome: 5200000,
      monthlyExpenses: 3100000,
      disposableIncome: 2100000,
      debtToIncomeRatio: 34.0,
      creditScore: 710,
      riskGrade: 'MEDIUM',
      recommendation: 'RECOMMEND_APPROVE',
      notes: 'Strong farm assets, stable local market off-takers in Arusha city hotels.',
    },
    approvals: [],
    createdAt: '2024-09-04T11:00:00Z',
    updatedAt: '2024-09-05T14:20:00Z',
  },
];

export const INITIAL_SAVINGS: SavingsAccount[] = [
  {
    id: 'sa-grace-01',
    accountNumber: 'SA-2024-009101',
    customerId: 'cust-grace',
    customerName: 'Grace Emanuel Kimaro',
    branchId: 'br-kariakoo',
    productType: 'COMPULSORY_COLLATERAL',
    interestRate: 4.5,
    balance: 500000, // 20% compulsory collateral for 2.5M loan
    lockedAmount: 500000,
    status: 'ACTIVE',
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'sa-grace-02',
    accountNumber: 'SA-2024-009102',
    customerId: 'cust-grace',
    customerName: 'Grace Emanuel Kimaro',
    branchId: 'br-kariakoo',
    productType: 'VOLUNTARY',
    interestRate: 6.0,
    balance: 850000,
    lockedAmount: 0,
    status: 'ACTIVE',
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'sa-zawadi-01',
    accountNumber: 'SA-2024-009103',
    customerId: 'cust-zawadi',
    customerName: 'Zawadi Joseph Mrema',
    branchId: 'br-kariakoo',
    productType: 'VOLUNTARY',
    interestRate: 6.0,
    balance: 320000,
    lockedAmount: 0,
    status: 'ACTIVE',
    createdAt: '2024-03-05T12:00:00Z',
  },
];

export const INITIAL_CHART_OF_ACCOUNTS: ChartOfAccount[] = [
  { id: 'coa-1010', code: '1010', name: 'Cash at Branch Vault / Till', type: 'ASSET', normalBalance: 'DEBIT', balance: 14500000 },
  { id: 'coa-1020', code: '1020', name: 'Vodacom M-Pesa Float Account', type: 'ASSET', normalBalance: 'DEBIT', balance: 38200000 },
  { id: 'coa-1030', code: '1030', name: 'CRDB Bank Corporate Account', type: 'ASSET', normalBalance: 'DEBIT', balance: 92400000 },
  { id: 'coa-1210', code: '1210', name: 'Gross Loan Portfolio (Principal Receivable)', type: 'ASSET', normalBalance: 'DEBIT', balance: 4583333 },
  { id: 'coa-1220', code: '1220', name: 'Accrued Interest Receivable', type: 'ASSET', normalBalance: 'DEBIT', balance: 292500 },
  { id: 'coa-2010', code: '2010', name: 'Customer Compulsory Collateral Savings', type: 'LIABILITY', normalBalance: 'CREDIT', balance: 500000 },
  { id: 'coa-2020', code: '2020', name: 'Customer Voluntary Savings Deposits', type: 'LIABILITY', normalBalance: 'CREDIT', balance: 1170000 },
  { id: 'coa-3010', code: '3010', name: 'Paid-in Share Capital', type: 'EQUITY', normalBalance: 'CREDIT', balance: 125000000 },
  { id: 'coa-4010', code: '4010', name: 'Loan Interest Income', type: 'INCOME', normalBalance: 'CREDIT', balance: 1125000 },
  { id: 'coa-4020', code: '4020', name: 'Loan Processing Fees Income', type: 'INCOME', normalBalance: 'CREDIT', balance: 142500 },
  { id: 'coa-4030', code: '4030', name: 'Late Repayment Penalty Income', type: 'INCOME', normalBalance: 'CREDIT', balance: 45000 },
];

export const INITIAL_JOURNALS: JournalEntry[] = [
  {
    id: 'je-init-1',
    entryNumber: 'JV-2024-000101',
    branchId: 'br-kariakoo',
    transactionDate: '2024-02-01',
    narration: 'Disbursement of Loan LN-2024-001091 to Grace Emanuel Kimaro',
    referenceType: 'LOAN_DISBURSEMENT',
    referenceId: 'LN-2024-001091',
    postedBy: 'Juma Mussa',
    lines: [
      { id: 'jl-1-1', accountId: 'coa-1210', accountCode: '1210', accountName: 'Gross Loan Portfolio', entryType: 'DEBIT', amount: 2500000 },
      { id: 'jl-1-2', accountId: 'coa-1020', accountCode: '1020', accountName: 'Vodacom M-Pesa Float', entryType: 'CREDIT', amount: 2437500 },
      { id: 'jl-1-3', accountId: 'coa-4020', accountCode: '4020', accountName: 'Processing Fees Income', entryType: 'CREDIT', amount: 62500 },
    ],
    totalDebit: 2500000,
    totalCredit: 2500000,
    createdAt: '2024-02-01T10:05:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    userId: 'usr-baraka',
    userName: 'Baraka Mkumbo',
    userRole: 'BRANCH_MANAGER',
    action: 'LOAN_DISBURSEMENT_APPROVED',
    entityName: 'loan_applications',
    entityId: 'app-grace-01',
    beforeState: { status: 'PENDING_APPROVAL', approvedPrincipal: null },
    afterState: { status: 'DISBURSED', approvedPrincipal: 2500000 },
    ipAddress: '197.250.48.12',
    timestamp: '2024-02-01T10:00:00Z',
  },
  {
    id: 'aud-2',
    userId: 'usr-juma',
    userName: 'Juma Mussa',
    userRole: 'ACCOUNTANT',
    action: 'JOURNAL_ENTRY_POSTED',
    entityName: 'journal_entries',
    entityId: 'je-init-1',
    beforeState: null,
    afterState: { entryNumber: 'JV-2024-000101', totalDebit: 2500000, totalCredit: 2500000 },
    ipAddress: '197.250.48.14',
    timestamp: '2024-02-01T10:06:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-seed-1',
    receiptNumber: 'RCP-20240301-490211',
    loanId: 'ln-grace-01',
    loanAccountNumber: 'LN-2024-001091',
    customerName: 'Grace Emanuel Kimaro',
    branchId: 'br-kariakoo',
    amount: 454167,
    paymentMethod: 'MOBILE_MONEY',
    channelReference: 'MPESA-QKW89102K',
    paymentDate: '2024-03-01T12:30:00Z',
    receivedBy: 'System Webhook (M-Pesa)',
    idempotencyKey: 'idemp-mpesa-qkw89102k',
    isReversed: false,
    allocations: [
      {
        id: 'alloc-seed-1',
        installmentId: 'inst-ln-grace-01-1',
        installmentNumber: 1,
        allocatedPenalty: 0,
        allocatedFee: 0,
        allocatedInterest: 37500,
        allocatedPrincipal: 416667,
        totalAllocated: 454167,
      },
    ],
  },
];
