import { getDb } from './index.ts';
import * as schema from './schema.ts';
import { count } from 'drizzle-orm';
import bcrypt from 'bcryptjs';

export async function seedDatabaseIfEmpty() {
  const { db } = getDb();

  const [{ count: branchCount }] = await db.select({ count: count() }).from(schema.branches);
  if (Number(branchCount) > 0) {
    return;
  }

  console.log('Seeding initial Tanzania Microfinance operational data...');

  const defaultPasswordHash = bcrypt.hashSync('Imara@2025', 10);

  // 1. Branches
  await db.insert(schema.branches).values([
    {
      id: 'br-kariakoo',
      code: 'DAR-01',
      name: 'Kariakoo Main Branch',
      region: 'Dar es Salaam',
      address: 'Msimbazi & Narung’ombe Street, Kariakoo',
      phone: '+255 22 218 0400',
      isActive: true,
    },
    {
      id: 'br-arusha',
      code: 'ARU-01',
      name: 'Arusha Clock Tower Branch',
      region: 'Arusha',
      address: 'Boma Road, Near Clock Tower',
      phone: '+255 27 250 8820',
      isActive: true,
    },
    {
      id: 'br-mwanza',
      code: 'MWA-01',
      name: 'Mwanza Rock City Branch',
      region: 'Mwanza',
      address: 'Kenyatta Road, Nyamagana',
      phone: '+255 28 250 0411',
      isActive: true,
    },
  ]);

  // 2. Users with Hashed Passwords & Unique Usernames
  await db.insert(schema.users).values([
    {
      id: 'usr-amina',
      username: 'amina.ho',
      email: 'amina.mwamba@tusonge-mfi.co.tz',
      passwordHash: defaultPasswordHash,
      firstName: 'Amina',
      lastName: 'Mwamba',
      role: 'HEAD_OFFICE_MANAGER',
      branchId: 'br-kariakoo',
      preferredLanguage: 'en',
      isActive: true,
    },
    {
      id: 'usr-baraka',
      username: 'baraka.bm',
      email: 'baraka.mkumbo@tusonge-mfi.co.tz',
      passwordHash: defaultPasswordHash,
      firstName: 'Baraka',
      lastName: 'Mkumbo',
      role: 'BRANCH_MANAGER',
      branchId: 'br-kariakoo',
      preferredLanguage: 'sw',
      isActive: true,
    },
    {
      id: 'usr-daudi',
      username: 'daudi.lo',
      email: 'daudi.kibona@tusonge-mfi.co.tz',
      passwordHash: defaultPasswordHash,
      firstName: 'Daudi',
      lastName: 'Kibona',
      role: 'LOAN_OFFICER',
      branchId: 'br-kariakoo',
      preferredLanguage: 'sw',
      isActive: true,
    },
    {
      id: 'usr-rehema',
      username: 'rehema.co',
      email: 'rehema.shaban@tusonge-mfi.co.tz',
      passwordHash: defaultPasswordHash,
      firstName: 'Rehema',
      lastName: 'Shaban',
      role: 'COLLECTION_OFFICER',
      branchId: 'br-kariakoo',
      preferredLanguage: 'sw',
      isActive: true,
    },
    {
      id: 'usr-juma',
      username: 'juma.acc',
      email: 'juma.mussa@tusonge-mfi.co.tz',
      passwordHash: defaultPasswordHash,
      firstName: 'Juma',
      lastName: 'Mussa',
      role: 'ACCOUNTANT',
      branchId: 'br-kariakoo',
      preferredLanguage: 'en',
      isActive: true,
    },
    {
      id: 'usr-neema',
      username: 'neema.aud',
      email: 'neema.lyimo@tusonge-mfi.co.tz',
      passwordHash: defaultPasswordHash,
      firstName: 'Neema',
      lastName: 'Lyimo',
      role: 'AUDITOR',
      branchId: 'br-kariakoo',
      preferredLanguage: 'en',
      isActive: true,
    },
  ]);

  // 3. Chart of Accounts (BOT Standard)
  await db.insert(schema.chartOfAccounts).values([
    { id: 'coa-1010', code: '1010', name: 'Cash in Vault (Taslimu)', type: 'ASSET', normalBalance: 'DEBIT', balance: 14500000, description: 'Physical cash at teller & safe' },
    { id: 'coa-1020', code: '1020', name: 'M-Pesa B2C/C2B Settlement', type: 'ASSET', normalBalance: 'DEBIT', balance: 38250000, description: 'Vodacom M-Pesa float account' },
    { id: 'coa-1030', code: '1030', name: 'Airtel Money Settlement', type: 'ASSET', normalBalance: 'DEBIT', balance: 12400000, description: 'Airtel Money business float' },
    { id: 'coa-1040', code: '1040', name: 'Tigo Pesa Settlement', type: 'ASSET', normalBalance: 'DEBIT', balance: 15600000, description: 'Mixx by Yas Tigo Pesa collection' },
    { id: 'coa-1050', code: '1050', name: 'CRDB Bank Operational', type: 'ASSET', normalBalance: 'DEBIT', balance: 84000000, description: 'CRDB Bank commercial clearing account' },
    { id: 'coa-1200', code: '1200', name: 'Gross Loan Portfolio', type: 'ASSET', normalBalance: 'DEBIT', balance: 126500000, description: 'Principal outstanding across all loan products' },
    { id: 'coa-1210', code: '1210', name: 'Allowance for Loan Impairment', type: 'ASSET', normalBalance: 'CREDIT', balance: 4200000, description: 'BOT regulated loan loss provisioning' },
    { id: 'coa-2010', code: '2010', name: 'Customer Voluntary Savings', type: 'LIABILITY', normalBalance: 'CREDIT', balance: 64800000, description: 'Member withdrawable savings balances' },
    { id: 'coa-2020', code: '2020', name: 'Compulsory Collateral Savings', type: 'LIABILITY', normalBalance: 'CREDIT', balance: 32500000, description: 'Pledged 10% loan security reserves' },
    { id: 'coa-3010', code: '3010', name: 'Institutional Capital', type: 'EQUITY', normalBalance: 'CREDIT', balance: 150000000, description: 'Initial paid-up microfinance capital' },
    { id: 'coa-3020', code: '3020', name: 'Retained Surplus Earnings', type: 'EQUITY', normalBalance: 'CREDIT', balance: 25450000, description: 'Accumulated operational surplus' },
    { id: 'coa-4010', code: '4010', name: 'Interest on Loans', type: 'INCOME', normalBalance: 'CREDIT', balance: 14850000, description: 'Earned interest on microfinance facilities' },
    { id: 'coa-4020', code: '4020', name: 'Loan Origination & Processing Fees', type: 'INCOME', normalBalance: 'CREDIT', balance: 3200000, description: 'Upfront 2% loan processing fees' },
    { id: 'coa-4030', code: '4030', name: 'Late Payment Penalties', type: 'INCOME', normalBalance: 'CREDIT', balance: 450000, description: 'Daily late charge accruals' },
    { id: 'coa-5010', code: '5010', name: 'Provision for Impairment Expense', type: 'EXPENSE', normalBalance: 'DEBIT', balance: 2100000, description: 'Monthly impairment adjustments' },
    { id: 'coa-5020', code: '5020', name: 'Telco C2B/B2C Transaction Fees', type: 'EXPENSE', normalBalance: 'DEBIT', balance: 1250000, description: 'Network tariff charges' },
    { id: 'coa-5030', code: '5030', name: 'General Branch Administration', type: 'EXPENSE', normalBalance: 'DEBIT', balance: 4800000, description: 'Rent, field travel, electricity, IT' },
  ]);

  // 4. Loan Products
  await db.insert(schema.loanProducts).values([
    {
      id: 'prod-biashara',
      code: 'BIASHARA-01',
      nameEn: 'Kariakoo Biashara Micro-Loan',
      nameSw: 'Mkopo wa Biashara Ndogo ya Kariakoo',
      interestMethod: 'REDUCING_EQUAL_INSTALLMENT',
      annualInterestRate: 18.0,
      minAmount: 500000,
      maxAmount: 10000000,
      minTenureMonths: 3,
      maxTenureMonths: 18,
      repaymentFrequency: 'MONTHLY',
      originationFeeRate: 0.02,
      compulsorySavingsRate: 0.10,
      penaltyRatePerDay: 0.001,
      gracePeriodDays: 5,
      isActive: true,
    },
    {
      id: 'prod-kilimo',
      code: 'KILIMO-02',
      nameEn: 'Kilimo Agribusiness Facility',
      nameSw: 'Mkopo wa Wakulima na Wafugaji',
      interestMethod: 'REDUCING_EQUAL_PRINCIPAL',
      annualInterestRate: 15.0,
      minAmount: 1000000,
      maxAmount: 25000000,
      minTenureMonths: 6,
      maxTenureMonths: 36,
      repaymentFrequency: 'MONTHLY',
      originationFeeRate: 0.015,
      compulsorySavingsRate: 0.08,
      penaltyRatePerDay: 0.0008,
      gracePeriodDays: 14,
      isActive: true,
    },
    {
      id: 'prod-tupendane',
      code: 'SOLIDARITY-03',
      nameEn: 'Tupendane Solidarity Group Loan',
      nameSw: 'Mkopo wa Kikundi cha Mshikamano',
      interestMethod: 'FLAT',
      annualInterestRate: 20.0,
      minAmount: 200000,
      maxAmount: 3000000,
      minTenureMonths: 3,
      maxTenureMonths: 12,
      repaymentFrequency: 'WEEKLY',
      originationFeeRate: 0.025,
      compulsorySavingsRate: 0.12,
      penaltyRatePerDay: 0.0015,
      gracePeriodDays: 3,
      isActive: true,
    },
  ]);

  // 5. Groups
  await db.insert(schema.groups).values([
    {
      id: 'grp-1',
      groupNumber: 'GRP-DAR-001',
      name: 'Tupendane Women Traders Group',
      meetingDay: 'Tuesday',
      meetingFrequency: 'WEEKLY',
      meetingLocation: 'Kariakoo Market Hall B, Dar es Salaam',
      branchId: 'br-kariakoo',
      officerId: 'usr-co-1',
      isActive: true,
    },
    {
      id: 'grp-2',
      groupNumber: 'GRP-ARU-002',
      name: 'Arusha Green Farmers Solidarity',
      meetingDay: 'Thursday',
      meetingFrequency: 'BI_WEEKLY',
      meetingLocation: 'Mianzini Community Center, Arusha',
      branchId: 'br-arusha',
      officerId: 'usr-co-1',
      isActive: true,
    },
  ]);

  // 6. Customers
  await db.insert(schema.customers).values([
    {
      id: 'cust-1',
      customerNumber: 'CUST-2024-001',
      firstName: 'Asha',
      lastName: 'Shabani',
      nationalIdNida: '19880415-11202-00001-24',
      phoneNumber: '+255754123456',
      email: 'asha.shabani@gmail.com',
      dateOfBirth: '1988-04-15',
      gender: 'FEMALE',
      residentialAddress: 'Kariakoo, Msimbazi St, Dar es Salaam',
      businessType: 'Vitenge & Textile Wholesale',
      monthlyIncome: 2400000,
      branchId: 'br-kariakoo',
      kycTier: 3,
      crbStatus: 'EXCELLENT',
      crbScore: 785,
      latitude: -6.8162,
      longitude: 39.2789,
    },
    {
      id: 'cust-2',
      customerNumber: 'CUST-2024-002',
      firstName: 'Hamisi',
      lastName: 'Omari',
      nationalIdNida: '19930722-21104-00002-18',
      phoneNumber: '+255768987654',
      email: 'hamisi.omari@yahoo.com',
      dateOfBirth: '1993-07-22',
      gender: 'MALE',
      residentialAddress: 'Ilala Boma, Dar es Salaam',
      businessType: 'Transport & Logistics (Bodaboda Fleet)',
      monthlyIncome: 1650000,
      branchId: 'br-kariakoo',
      kycTier: 2,
      crbStatus: 'GOOD',
      crbScore: 712,
      latitude: -6.8245,
      longitude: 39.2632,
    },
    {
      id: 'cust-3',
      customerNumber: 'CUST-2024-003',
      firstName: 'Grace',
      lastName: 'Lyimo',
      nationalIdNida: '19851103-31109-00003-91',
      phoneNumber: '+255713554433',
      email: 'grace.lyimo@hotmail.com',
      dateOfBirth: '1985-11-03',
      gender: 'FEMALE',
      residentialAddress: 'Mianzini, Arusha',
      businessType: 'Fresh Produce & Vegetable Farming',
      monthlyIncome: 3800000,
      branchId: 'br-arusha',
      kycTier: 3,
      crbStatus: 'EXCELLENT',
      crbScore: 820,
      latitude: -3.3667,
      longitude: 36.6833,
    },
    {
      id: 'cust-4',
      customerNumber: 'CUST-2024-004',
      firstName: 'Baraka',
      lastName: 'Mrema',
      nationalIdNida: '19900218-41208-00004-55',
      phoneNumber: '+255784667890',
      email: null,
      dateOfBirth: '1990-02-18',
      gender: 'MALE',
      residentialAddress: 'Usa River, Arusha',
      businessType: 'Commercial Poultry & Eggs',
      monthlyIncome: 2100000,
      branchId: 'br-arusha',
      kycTier: 2,
      crbStatus: 'FAIR',
      crbScore: 654,
      latitude: -3.3721,
      longitude: 36.8524,
    },
    {
      id: 'cust-5',
      customerNumber: 'CUST-2024-005',
      firstName: 'Fatuma',
      lastName: 'Rashid',
      nationalIdNida: '19890910-51101-00005-72',
      phoneNumber: '+255752334455',
      email: null,
      dateOfBirth: '1989-09-10',
      gender: 'FEMALE',
      residentialAddress: 'Gerezani, Dar es Salaam',
      businessType: 'Mama Lishe Restaurant Catering',
      monthlyIncome: 1850000,
      branchId: 'br-kariakoo',
      kycTier: 2,
      crbStatus: 'GOOD',
      crbScore: 690,
      latitude: -6.8288,
      longitude: 39.2812,
    },
  ]);

  // Group Members
  await db.insert(schema.groupMembers).values([
    { id: 'gm-1', groupId: 'grp-1', customerId: 'cust-1', roleInGroup: 'CHAIRPERSON' },
    { id: 'gm-2', groupId: 'grp-1', customerId: 'cust-5', roleInGroup: 'TREASURER' },
    { id: 'gm-3', groupId: 'grp-2', customerId: 'cust-3', roleInGroup: 'SECRETARY' },
    { id: 'gm-4', groupId: 'grp-2', customerId: 'cust-4', roleInGroup: 'MEMBER' },
  ]);

  // 7. Savings Accounts
  await db.insert(schema.savingsAccounts).values([
    {
      id: 'sav-1',
      accountNumber: 'SAV-TZS-1001',
      customerId: 'cust-1',
      productType: 'VOLUNTARY',
      balance: 1850000,
      lockedAmount: 500000,
      status: 'ACTIVE',
    },
    {
      id: 'sav-2',
      accountNumber: 'SAV-TZS-1002',
      customerId: 'cust-2',
      productType: 'VOLUNTARY',
      balance: 740000,
      lockedAmount: 300000,
      status: 'ACTIVE',
    },
    {
      id: 'sav-3',
      accountNumber: 'SAV-TZS-1003',
      customerId: 'cust-3',
      productType: 'VOLUNTARY',
      balance: 4200000,
      lockedAmount: 1000000,
      status: 'ACTIVE',
    },
    {
      id: 'sav-4',
      accountNumber: 'SAV-TZS-1004',
      customerId: 'cust-4',
      productType: 'COMPULSORY_COLLATERAL',
      balance: 600000,
      lockedAmount: 600000,
      status: 'ACTIVE',
    },
    {
      id: 'sav-5',
      accountNumber: 'SAV-TZS-1005',
      customerId: 'cust-5',
      productType: 'VOLUNTARY',
      balance: 920000,
      lockedAmount: 200000,
      status: 'ACTIVE',
    },
  ]);

  // 8. Loan Applications & Active Loans
  await db.insert(schema.loanApplications).values([
    {
      id: 'app-1',
      applicationNumber: 'APP-2024-001',
      customerId: 'cust-1',
      productId: 'prod-biashara',
      groupId: 'grp-1',
      requestedAmount: 5000000,
      approvedAmount: 5000000,
      tenureMonths: 12,
      purpose: 'Expansion of vitenge stock ahead of Eid shopping season',
      status: 'DISBURSED',
      assessedDsti: 0.32,
      creditScore: 785,
      officerRecommendation: 'Strong cashflow, dependable group guarantee.',
      reviewedBy: 'usr-bm-1',
    },
    {
      id: 'app-2',
      applicationNumber: 'APP-2024-002',
      customerId: 'cust-2',
      productId: 'prod-biashara',
      groupId: null,
      requestedAmount: 3000000,
      approvedAmount: 3000000,
      tenureMonths: 8,
      purpose: 'Down payment for 2nd motorcycle on Bajaj contract',
      status: 'DISBURSED',
      assessedDsti: 0.28,
      creditScore: 712,
      officerRecommendation: 'Regular daily M-Pesa statements verified.',
      reviewedBy: 'usr-bm-1',
    },
    {
      id: 'app-3',
      applicationNumber: 'APP-2024-003',
      customerId: 'cust-3',
      productId: 'prod-kilimo',
      groupId: 'grp-2',
      requestedAmount: 10000000,
      approvedAmount: 10000000,
      tenureMonths: 18,
      purpose: 'Installation of solar water pump and drip irrigation kit',
      status: 'DISBURSED',
      assessedDsti: 0.25,
      creditScore: 820,
      officerRecommendation: 'Excellent grower history, off-taker agreements in place.',
      reviewedBy: 'usr-bm-1',
    },
    {
      id: 'app-4',
      applicationNumber: 'APP-2024-004',
      customerId: 'cust-4',
      productId: 'prod-kilimo',
      groupId: 'grp-2',
      requestedAmount: 6000000,
      approvedAmount: 6000000,
      tenureMonths: 12,
      purpose: 'Purchasing 2000 day-old chicks and 3 months feed inventory',
      status: 'DISBURSED',
      assessedDsti: 0.38,
      creditScore: 654,
      officerRecommendation: 'Poultry barn inspected. Risk mitigated by group guarantee.',
      reviewedBy: 'usr-bm-1',
    },
    {
      id: 'app-5',
      applicationNumber: 'APP-2024-005',
      customerId: 'cust-5',
      productId: 'prod-tupendane',
      groupId: 'grp-1',
      requestedAmount: 1500000,
      approvedAmount: null,
      tenureMonths: 6,
      purpose: 'Kitchen industrial equipment upgrade for catering contracts',
      status: 'PENDING_REVIEW',
      assessedDsti: 0.29,
      creditScore: 690,
      officerRecommendation: 'Recommended for approval with 10% compulsory savings.',
      reviewedBy: null,
    },
  ]);

  // 9. Active Loans
  await db.insert(schema.loans).values([
    {
      id: 'loan-1',
      loanAccountNumber: 'LN-DAR-0001',
      applicationId: 'app-1',
      customerId: 'cust-1',
      productId: 'prod-biashara',
      branchId: 'br-kariakoo',
      groupId: 'grp-1',
      principalAmount: 5000000,
      outstandingPrincipal: 3350000,
      interestRate: 18.0,
      tenureMonths: 12,
      disbursementDate: '2024-01-15',
      maturityDate: '2025-01-15',
      status: 'ACTIVE',
      interestMethod: 'REDUCING_EQUAL_INSTALLMENT',
      repaymentFrequency: 'MONTHLY',
      daysInArrears: 0,
      accruedInterest: 0,
      unpaidFees: 0,
      unpaidPenalties: 0,
      totalPaid: 2075000,
    },
    {
      id: 'loan-2',
      loanAccountNumber: 'LN-DAR-0002',
      applicationId: 'app-2',
      customerId: 'cust-2',
      productId: 'prod-biashara',
      branchId: 'br-kariakoo',
      groupId: null,
      principalAmount: 3000000,
      outstandingPrincipal: 1900000,
      interestRate: 18.0,
      tenureMonths: 8,
      disbursementDate: '2024-02-01',
      maturityDate: '2024-10-01',
      status: 'ACTIVE',
      interestMethod: 'REDUCING_EQUAL_INSTALLMENT',
      repaymentFrequency: 'MONTHLY',
      daysInArrears: 0,
      accruedInterest: 0,
      unpaidFees: 0,
      unpaidPenalties: 0,
      totalPaid: 1350000,
    },
    {
      id: 'loan-3',
      loanAccountNumber: 'LN-ARU-0003',
      applicationId: 'app-3',
      customerId: 'cust-3',
      productId: 'prod-kilimo',
      branchId: 'br-arusha',
      groupId: 'grp-2',
      principalAmount: 10000000,
      outstandingPrincipal: 7800000,
      interestRate: 15.0,
      tenureMonths: 18,
      disbursementDate: '2024-01-10',
      maturityDate: '2025-07-10',
      status: 'ACTIVE',
      interestMethod: 'REDUCING_EQUAL_PRINCIPAL',
      repaymentFrequency: 'MONTHLY',
      daysInArrears: 0,
      accruedInterest: 0,
      unpaidFees: 0,
      unpaidPenalties: 0,
      totalPaid: 3100000,
    },
    {
      id: 'loan-4',
      loanAccountNumber: 'LN-ARU-0004',
      applicationId: 'app-4',
      customerId: 'cust-4',
      productId: 'prod-kilimo',
      branchId: 'br-arusha',
      groupId: 'grp-2',
      principalAmount: 6000000,
      outstandingPrincipal: 5200000,
      interestRate: 15.0,
      tenureMonths: 12,
      disbursementDate: '2024-02-15',
      maturityDate: '2025-02-15',
      status: 'DELINQUENT',
      interestMethod: 'REDUCING_EQUAL_PRINCIPAL',
      repaymentFrequency: 'MONTHLY',
      daysInArrears: 38,
      accruedInterest: 65000,
      unpaidFees: 20000,
      unpaidPenalties: 19760,
      totalPaid: 1100000,
    },
  ]);

  // 10. Sample Repayments
  await db.insert(schema.repayments).values([
    {
      id: 'rep-1',
      receiptNumber: 'RCP-2024-0091',
      loanId: 'loan-1',
      amount: 458000,
      paymentDate: '2024-05-15',
      paymentMethod: 'MPESA',
      referenceNumber: 'SK72HQ9120',
      principalAllocated: 385000,
      interestAllocated: 73000,
      feesAllocated: 0,
      penaltiesAllocated: 0,
      receivedBy: 'C2B_AUTOMATION',
    },
    {
      id: 'rep-2',
      receiptNumber: 'RCP-2024-0092',
      loanId: 'loan-2',
      amount: 420000,
      paymentDate: '2024-05-18',
      paymentMethod: 'AIRTEL_MONEY',
      referenceNumber: 'AIR882190',
      principalAllocated: 365000,
      interestAllocated: 55000,
      feesAllocated: 0,
      penaltiesAllocated: 0,
      receivedBy: 'usr-cash-1',
    },
    {
      id: 'rep-3',
      receiptNumber: 'RCP-2024-0093',
      loanId: 'loan-3',
      amount: 680000,
      paymentDate: '2024-05-20',
      paymentMethod: 'TIGO_PESA',
      referenceNumber: 'TG9912048',
      principalAllocated: 555000,
      interestAllocated: 125000,
      feesAllocated: 0,
      penaltiesAllocated: 0,
      receivedBy: 'usr-cash-1',
    },
  ]);

  // 11. Initial Audit Logs
  await db.insert(schema.auditLogs).values([
    {
      id: 'log-1',
      userId: 'usr-bm-1',
      userName: 'John Mwangi',
      userRole: 'BRANCH_MANAGER',
      action: 'SYSTEM_INITIALIZATION',
      entityName: 'SYSTEM',
      entityId: 'SYS-INIT',
      ipAddress: '192.168.1.10',
      details: 'Initialized Core Microfinance Database schema, BOT chart of accounts, and Dar es Salaam branches.',
    },
    {
      id: 'log-2',
      userId: 'usr-co-1',
      userName: 'Neema Amani',
      userRole: 'CREDIT_OFFICER',
      action: 'LOAN_APPLICATION_CREATE',
      entityName: 'LOAN_APPLICATION',
      entityId: 'app-1',
      ipAddress: '10.0.4.52',
      details: 'Captured field application for Asha Shabani (Kariakoo Market Women Group).',
    },
    {
      id: 'log-3',
      userId: 'usr-bm-1',
      userName: 'John Mwangi',
      userRole: 'BRANCH_MANAGER',
      action: 'LOAN_DISBURSEMENT',
      entityName: 'LOAN',
      entityId: 'loan-1',
      ipAddress: '192.168.1.10',
      details: 'Disbursed TZS 5,000,000 to Asha Shabani via M-Pesa B2C batch.',
    },
  ]);

  console.log('Database seeded successfully.');
}
